baseURL = "https://www.ethanzhang.xyz/"
# [en, zh-cn, fr, pl, ...] determines default content language
# [en, zh-cn, fr, pl, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# theme
# 主题
theme = "LoveIt"
# themes directory
# 主题目录
#themesDir = "../.."

publishDir ="docs"
# website title
# 网站标题
title = "谢先生健身房"

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = false
# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true

[languages]
  [languages.zh-cn]
   [languages.zh-cn.params]
        # 网站描述
        description = "谢先生的个人博客"
        # 网站关键词
        keywords = ["Linux", "云原生","Golang"]
        # 应用图标配置
        [languages.zh-cn.params.app]
          # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
          title = "谢先生健身房"
          # 是否隐藏网站图标资源链接
          noFavicon = false
          # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
          svgFavicon = ""
          # Android 浏览器主题色
          themeColor = "#ffffff"
          # Safari 图标颜色
          iconColor = "#5bbad5"
          # Windows v8-10 磁贴颜色
          tileColor = "#da532c"
      [languages.zh-cn.params.home]
        # RSS 文章数目
        rss = 10
        # 主页个人信息
        [languages.zh-cn.params.home.profile]
          enable = true
          # Gravatar 邮箱，用于优先在主页显示的头像
          gravatarEmail = ""
          # 主页显示头像的 URL
          # avatarURL = "/images/avatar.png"
          # 主页显示的网站标题 (支持 HTML 格式)
          title = ""
          # 主页显示的网站副标题
          subtitle = "Linux 云技术 编程"
          # 是否为副标题显示打字机动画
          typeit = true
          # 是否显示社交账号
          social = false
          # 免责声明 (支持 HTML 格式)
          disclaimer = ""

        # 搜索配置
      [languages.zh-cn.params.search]
        enable = true
        # 搜索引擎的类型 ("lunr", "algolia")
        type = "algolia"
        # 文章内容最长索引长度
        contentLength = 4000

[languages.zh-cn.menu]
  [[languages.zh-cn.menu.main]]
      identifier = "posts"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      name = "所有文章"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.zh-cn.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.zh-cn.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
      weight = 3
    [[languages.zh-cn.menu.main]]
        identifier = "research"
        pre = ""
        name = "科研生活"
        url = ""
        title = ""
        weight = 4

    [[languages.zh-cn.menu.main]]
        identifier = "door"
        pre = ""
        name = "传送门"
        url = ""
        title = ""
        weight = 5
    # 导航栏二级菜单
    [[languages.zh-cn.menu.main]]
      identifier = "friends"
      pre = ""
      post = "_blank"
      name = "友链"
      url = "/friends/"
      title = ""
      weight = 5
      parent = "door"
    [[languages.zh-cn.menu.main]]
      parent = "door"
      identifier = "message"
      pre = ""
      post = ""
      name = "留言板"
      url = "/message/"
      title = ""
      weight = 5
    [[languages.zh-cn.menu.main]]
      parent = "door"
      identifier = "about"
      pre = ""
      post = ""
      name = "关于"
      url = "/about/"
      title = ""
      weight = 5

    [[languages.zh-cn.menu.main]]
      identifier = "gitee"
      pre = "<i class='fab fa-github' style='color:red'></i>"
      post = ""
      name = ""
      url = "https://gitee.com/xieliangcai"
      title = "gitee"
      weight = 6
    [[languages.zh-cn.menu.main]]
      identifier = "github"
      pre = "<i class='fab fa-github' style='color:black'></i>"
      post = ""
      name = ""
      url = "https://GitHub.com/xieliangcai"
      title = "GitHub"
      weight = 7


[params.footer]
    enable = true
    # Custom content (HTML format is supported)
    # 自定义内容 (支持 HTML 格式)
    custom = ''
    # whether to show Hugo and theme info
    # 是否显示 Hugo 和主题信息
    hugo = false
    # whether to show copyright info
    # 是否显示版权信息
    copyright = true
    # whether to show the author
    # 是否显示作者
    author = true
    # site creation time
    # 网站创立年份
    since = 2020
    # ICP info only in China (HTML format is supported)
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = "沪ICP备 17000653号-2"
    # license info (HTML format is supported)
    # 许可协议信息 (支持 HTML 格式)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'


# [[languages.z
#   identifier
#   pre = ""
#   post = ""
#   name = "关于"
#   url = "/abo
#   title = ""
#   weight = 5
# [[languages.z
#   identifier
#   pre = "<i c
#   post = ""
#   name = ""
#   url = "http
#   title = "Gi
#   weight = 6

